name: docker build with cache

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: Display env
        run: env | sort | grep -e '^ACTIONS_'
      - name: expose environemnt variables
        uses: ./show-env-docker
      - name: Display env
        run: env | sort | grep -e '^ACTIONS_'
      # キャッシュをロードするはず
      - name: fast docker build with cache
        run: docker buildx build --cache-to=type=gha,mode=max --cache-from=type=gha .
      - name: Display env
        run: env | sort | grep -e '^ACTIONS_'